### ISSUE TITLE
feature request：光标样式修改

### ISSUE THREAD

**Issue by moonloadermic** [pdog18/rime-soak#10]
你好，我是win10 x64，小狼毫最新版本 weasel-0.15.0.0
默认的光标样式是 `^`（如图）
![默认光标样式](https://github.com/pdog18/rime-soak/assets/130746790/c3547a77-45a0-4ac4-b6a7-cfa0bd7ee3c4)

请问如何变成竖线光标样式 `|`，谢谢！🙏
 
![竖线光标样式](https://github.com/pdog18/rime-soak/assets/130746790/955fb382-f992-4e8b-bb6b-a2bfb360f413)

**Comment by pdog18** [comment]
您好，根据我的了解小狼毫目前不支持这个功能。
但是我也只是一个小白，也担心误导您，建议您可以在 rime 或者 weasel 进行咨询，您会得到更准确的回答。

**Comment by moonloadermic** [comment]
好的，谢谢！感谢你做的[rime-soak](https://pdog18.github.io/rime-soak/)，非常好用：）

**Comment by moonloadermic** [comment]
其实就是 
"style/inline_preedit": true

**Comment by pdog18** [comment]
> 其实就是
> "style/inline_preedit": true

根据我的了解，这个原因是用于编码区内联的，可能并不是开始时提到哦效果哦

**Comment by moonloadermic** [comment]
> 根据我的了解，这个原因是用于编码区内联的，可能并不是开始时提到哦效果哦

[内嵌编码/嵌入式編碼行](https://github.com/rime/home/wiki/CustomizationGuide#小狼毫外觀設定)，这个到底是什么，有什么效果，其实我不明白，如果您知道，还请科普一下。
不过就我自己而言，恕我愚笨，我没看出"style/inline_preedit": true/false 的区别，就是光标样式的区别啊。一个是`|`，一个是右下角的`^`，如图：

![1](https://github.com/pdog18/rime-soak/assets/130746790/4278ebfd-647d-4df1-af0c-a92f154001fa)

**Comment by pdog18** [comment]
您可以留意看下，这个 flag 的作用是用于编码区是否是在候选词面板上的哦。

如果是 true 那么编码区是显示在编辑区的光标处。
如果是 false 那么是显示在候选词面板上的。

您可以尝试调整一下您的候选词面板的背景色会比较直观。

**Comment by moonloadermic** [comment]
谢谢，我试一下。
